<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Editors can't change value for sync fields
 * @param $form
 * @param FormStateInterface $form_state
 * @param $form_id
 */
function joomigrate_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  $sync_fields = [
      'node_article_edit_form'        => \Drupal\joomigrate\Entity\Article::$sync_field,
      'media_image_edit_form'         => \Drupal\joomigrate\Entity\Image::$sync_field,
      'media_gallery_edit_form'       => \Drupal\joomigrate\Entity\Gallery::$sync_field,
      'taxonomy_term_channel_form'    => \Drupal\joomigrate\Entity\Channel::$sync_field,
      'taxonomy_term_tags_form'       => \Drupal\joomigrate\Entity\Tag::$sync_field,
      'user_form'                     => \Drupal\joomigrate\Entity\Author::$sync_field,
  ];

  foreach($sync_fields as $f => $s) {
      if($form_id == $f && isset($form[$s])){
          $form[$s]['widget'][0]['value']['#attributes']['disabled'] = 'disabled';
      }
  }
}
